#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_IRBEACON_YAW_ENABLED
#define AP_IRBEACON_YAW_ENABLED (BOARD_FLASH_SIZE > 1024)
#endif

#ifndef AP_IRBEACON_YAW_SITL_ENABLED
#define AP_IRBEACON_YAW_SITL_ENABLED (AP_IRBEACON_YAW_ENABLED && AP_SIM_ENABLED)
#endif
