#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_YAWBEACON_ENABLED
#define AP_YAWBEACON_ENABLED (BOARD_FLASH_SIZE > 1024)
#endif

#ifndef AP_YAWBEACON_SITL_ENABLED
#define AP_YAWBEACON_SITL_ENABLED (AP_YAWBEACON_ENABLED && AP_SIM_ENABLED)
#endif
